[network]
server_id = 9
servers_size = 16
[[network.servers]]
hostname = '11.158.244.107'
port = 11234
[[network.servers]]
hostname = '11.158.244.107'
port = 11235
[[network.servers]]
hostname = '11.158.244.107'
port = 11236
[[network.servers]]
hostname = '11.158.244.107'
port = 11237
[[network.servers]]
hostname = '11.158.244.107'
port = 11238
[[network.servers]]
hostname = '11.158.244.107'
port = 11239
[[network.servers]]
hostname = '11.158.244.107'
port = 11240
[[network.servers]]
hostname = '11.158.244.107'
port = 11241
[[network.servers]]
hostname = '11.158.244.107'
port = 11242
[[network.servers]]
hostname = '0.0.0.0'
port = 11243
[[network.servers]]
hostname = '11.158.244.107'
port = 11244
[[network.servers]]
hostname = '11.158.244.107'
port = 11245
[[network.servers]]
hostname = '11.158.244.107'
port = 11246
[[network.servers]]
hostname = '11.158.244.107'
port = 11247
[[network.servers]]
hostname = '11.158.244.107'
port = 11248
[[network.servers]]
hostname = '11.158.244.107'
port = 11249

